name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore NuGet packages
      run: nuget restore PasswordApp/PasswordApp.sln

    - name: Build
      run: msbuild PasswordApp/PasswordApp.sln /p:Configuration=Release /t:Rebuild

    - name: Publish
      run: msbuild PasswordApp/PasswordApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishDir=publish/

    - name: Upload Published Files
      uses: actions/upload-artifact@v4
      with:
        name: PasswordApp-Published
        path: PasswordApp/PasswordApp/bin/Release/
  