name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2    
      
    - name: Restore NuGet packages
      run: dotnet restore PasswordApp/PasswordApp.sln

    - name: Build
      run: dotnet build PasswordApp/PasswordApp.sln --configuration Release --no-restore
      
    - name: Run Tests
      run: dotnet test PasswordApp/PasswordApp.sln --configuration Release --verbosity normal

    - name: Publish
      if: success()
      run: dotnet publish PasswordApp/PasswordApp/PasswordApp.csproj -c Release -o ./publish

    - name: Upload Published Files
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: PasswordApp-Published
        path: PasswordApp/PasswordApp/bin/Release/
  